### PR TITLE
Updating zend framework 1 to last available version

### PR DESCRIPTION
**Pull request by mikeSimonson**

### CODE REVIEW

**Comment by wanderleihuttel** [comment]
Hello @mikeSimonson. 

If you will see, Webacula is already using zendframework 1.12.17dev.
I've took a look in the code and it looks there are only some files with differences, but I don't know why.

When I have a free time I will test the last one 1.12.20
https://framework.zend.com/downloads/archives

Thank you and best regards
Wanderlei

**Comment by mikeSimonson** [comment]
@wanderleihuttel 
That's the 1.12.20 that I updated to. (you get php 7 compatibility)

**Comment by wanderleihuttel** [comment]
You are right.
I've took a look in the wrong Branch.

**Comment by mikeSimonson** [comment]
Hi @wanderleihuttel,

Why did you closed it without merging it ?

**Comment by wanderleihuttel** [comment]
Hello @mikeSimonson! Because the permissions are different! 
I've already commited in the branch-7.5.

Thank you and best regards

**Pull request closed without merging**
